export const TEXTS_TABLE : {[language: string]: {[title: string]: string}} = {
	"English" : {
		"languageCode": "en",
		"Universal Declaration of Human Rights" :
			"<p>All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.</p>\n"+
			"<p>Everyone is entitled to all the rights and freedoms set forth in this Declaration, without distinction of any kind, such as race, colour, sex, language, religion, political or other opinion, national or social origin, property, birth or other status.</p>\n"+
			"<p>Furthermore, no distinction shall be made on the basis of the political, jurisdictional or international status of the country or territory to which a person belongs, whether it be independent, trust, non-self-governing or under any other limitation of sovereignty.</p>\n"+
			"<p>Everyone has the right to life, liberty and security of person.</p>",
		"Rainbow Passage (Grant Fairbanks)" :
			"<p>When the sunlight strikes raindrops in the air, they act as a prism and form a rainbow. The rainbow is a division of white light into many beautiful colors. These take the shape of a long round arch, with its path high above, and its two ends apparently beyond the horizon. There is, according to legend, a boiling pot of gold at one end. People look, but no one ever finds it. When a man looks for something beyond his reach, his friends say he is looking for the pot of gold at the end of the rainbow. Throughout the centuries people have explained the rainbow in various ways. Some have accepted it as a miracle without physical explanation. To the Hebrews it was a token that there would be no more universal floods. The Greeks used to imagine that it was a sign from the gods to foretell war or heavy rain. The Norsemen considered the rainbow as a bridge over which the gods passed from earth to their home in the sky. Others have tried to explain the phenomenon physically. Aristotle thought that the rainbow was caused by reflection of the sun's rays by the rain. Since then physicists have found that it is not reflection, but refraction by the raindrops which causes the rainbows. Many complicated ideas about the rainbow have been formed. The difference in the rainbow depends considerably upon the size of the drops, and the width of the colored band increases as the size of the drops increases. The actual primary rainbow observed is said to be the effect of super-imposition of a number of bows. If the red of the second bow falls upon the green of the first, the result is to give a bow with an abnormally wide yellow band, since red and green light when mixed form yellow. This is a very common type of bow, one showing mainly red and yellow, with little or no green or blue.</p>",
		"Grandfather Passage":
			"<p>You wished to know all about my grandfather. Well, he is nearly ninety-three years old. He dresses himself in an ancient black frock coat, usually minus several buttons; yet he still thinks as swiftly as ever. A long, flowing beard clings to his chin, giving those who observe him a pronounced feeling of the utmost respect. When he speaks his voice is just a bit cracked and quivers a trifle. Twice each day he plays skillfully and with zest upon our small organ. Except in the winter when the ooze or snow or ice prevents, he slowly takes a short walk in the open air each day. We have often urged him to walk more and smoke less, but he always answers, “Banana Oil!” Grandfather likes to be modern in his language.</p>"

	},
	"Deutsch" : {
		"languageCode": "de",
		"Allgemeine Erklärung der Menschenrechte" :
			"<p>Alle Menschen sind frei und gleich an Würde und Rechten geboren. Sie sind mit Vernunft und Gewissen begabt und sollen einander im Geist der Brüderlichkeit begegnen.</p>\n"+
			"<p>Jeder hat Anspruch auf die in dieser Erklärung verkündeten Rechte und Freiheiten ohne irgendeinen Unterschied, etwa nach Rasse, Hautfarbe, Geschlecht, Sprache, Religion, politischer oder sonstiger Überzeugung, nationaler oder sozialer Herkunft, Vermögen, Geburt oder sonstigem Stand.</p>\n"+
			"<p>Des weiteren darf kein Unterschied gemacht werden auf Grund der politischen, rechtlichen oder internationalen Stellung des Landes oder Gebiets, dem eine Person angehört, gleichgültig ob dieses unabhängig ist, unter Treuhandschaft steht, keine Selbstregierung besitzt oder sonst in seiner Souveränität eingeschränkt ist.</p>\n"+
			"<p>Jeder hat das Recht auf Leben, Freiheit und Sicherheit der Person.</p>",
		"Winnetou 1 (Karl May, 1893)" :
			"<p>Es war nicht nur eine gastliche Aufnahme, sondern eine beinahe göttliche Verehrung, welche die ersten ›Bleichgesichter‹ bei den Indsmen fanden. Welcher Lohn ist den Letzteren dafür geworden? Ganz unstreitig gehörte diesen das Land, welches sie bewohnten; es wurde ihnen genommen. Welche Ströme Blutes dabei geflossen und welche Grausamkeiten vorgekommen sind, das weiß ein Jeder, der die Geschichte der ›berühmten‹ Conquistadores gelesen hat. Nach dem Vorbilde derselben ist dann später weiter verfahren worden. Der Weiße kam mit süßen Worten auf den Lippen, aber zugleich mit dem geschärften Messer im Gürtel und dem geladenen Gewehre in der Hand. Er versprach Liebe und Frieden und gab Haß und Blut. Der Rote mußte weichen, Schritt um Schritt, immer weiter zurück. Von Zeit zu Zeit gewährleistete man ihm ›ewige‹ Rechte auf ›sein‹ Territorium, jagte ihn aber schon nach kurzer Zeit wieder aus demselben hinaus, weiter, immer weiter. Man ›kaufte‹ ihm das Land ab, bezahlte ihn aber entweder gar nicht oder mit wertlosen Tauschwaren, welche er nicht gebrauchen konnte. Aber das schleichende Gift des ›Feuerwassers‹ brachte man ihm desto sorgfältiger bei, dazu die Blattern und andere, noch viel schlimmere und ekelhaftere Krankheiten, welche ganze Stämme lichteten und ganze Dörfer entvölkerten. Wollte der Rote sein gutes Recht geltend machen, so antwortete man ihm mit Pulver und Blei, und er mußte den überlegenen Waffen der Weißen wieder weichen. Darüber erbittert, rächte er sich nun an dem einzelnen Bleichgesichte, welches ihm begegnete, und die Folgen davon waren dann stets förmliche Massacres, welche unter den Roten angerichtet wurden. Dadurch ist er, ursprünglich ein stolzer, kühner, tapferer, wahrheitsliebender, aufrichtiger und seinen Freunden stets treuer Jägersmann, ein heimlich schleichender, mißtrauischer, lügnerischer Mensch geworden, ohne daß er dafür kann, denn nicht er, sondern der Weiße ist schuld daran.</p>"
	},
	"Nederlands" : {
		"languageCode": "nl",
		"Universele Verklaring van de Rechten van de Mens":
			"<p>Alle mensen worden vrij en gelijk in waardigheid en rechten geboren. Zij zijn begiftigd met verstand en geweten, en behoren zich jegens elkander in een geest van broederschap te gedragen.</p>\n" +
			"<p>Een ieder heeft aanspraak op alle rechten en vrijheden, in deze Verklaring opgesomd, zonder enig onderscheid van welke aard ook, zoals ras, kleur, geslacht, taal, godsdienst, politieke of andere overtuiging, nationale of maatschappelijke afkomst, eigendom, geboorte of andere status.</p>\n" +
			"<p>Verder zal geen onderscheid worden gemaakt naar de politieke, juridische of internationale status van het land of gebied, waartoe iemand behoort, onverschillig of het een onafhankelijk, trust-, of niet-zelfbesturend gebied betreft, dan wel of er een andere beperking van de soevereiniteit bestaat.</p>\n" +
			"<p>Een ieder heeft het recht op leven, vrijheid en onschendbaarheid van zijn persoon. </p>\n"
	}
}
